<?php

use Illuminate\Database\Seeder;

class CountryTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $sql = "INSERT INTO `country` VALUES (null, 'AF', 'Afghanistan',null,null,1,null);
INSERT INTO `country` VALUES (null, 'AL', 'Albania',null,null,1,null);
INSERT INTO `country` VALUES (null, 'DZ', 'Algeria',null,null,1,null);
INSERT INTO `country` VALUES (null, 'DS', 'American Samoa',null,null,1,null);
INSERT INTO `country` VALUES (null, 'AD', 'Andorra',null,null,1,null);
INSERT INTO `country` VALUES (null, 'AO', 'Angola',null,null,1,null);
INSERT INTO `country` VALUES (null, 'AI', 'Anguilla',null,null,1,null);
INSERT INTO `country` VALUES (null, 'AQ', 'Antarctica',null,null,1,null);
INSERT INTO `country` VALUES (null, 'AG', 'Antigua and Barbuda',null,null,1,null);
INSERT INTO `country` VALUES (null, 'AR', 'Argentina',null,null,1,null);
INSERT INTO `country` VALUES (null, 'AM', 'Armenia',null,null,1,null);
INSERT INTO `country` VALUES (null, 'AW', 'Aruba',null,null,1,null);
INSERT INTO `country` VALUES (null, 'AU', 'Australia',null,null,1,null);
INSERT INTO `country` VALUES (null, 'AT', 'Austria',null,null,1,null);
INSERT INTO `country` VALUES (null, 'AZ', 'Azerbaijan',null,null,1,null);
INSERT INTO `country` VALUES (null, 'BS', 'Bahamas',null,null,1,null);
INSERT INTO `country` VALUES (null, 'BH', 'Bahrain',null,null,1,null);
INSERT INTO `country` VALUES (null, 'BD', 'Bangladesh',null,null,1,null);
INSERT INTO `country` VALUES (null, 'BB', 'Barbados',null,null,1,null);
INSERT INTO `country` VALUES (null, 'BY', 'Belarus',null,null,1,null);
INSERT INTO `country` VALUES (null, 'BE', 'Belgium',null,null,1,null);
INSERT INTO `country` VALUES (null, 'BZ', 'Belize',null,null,1,null);
INSERT INTO `country` VALUES (null, 'BJ', 'Benin',null,null,1,null);
INSERT INTO `country` VALUES (null, 'BM', 'Bermuda',null,null,1,null);
INSERT INTO `country` VALUES (null, 'BT', 'Bhutan',null,null,1,null);
INSERT INTO `country` VALUES (null, 'BO', 'Bolivia',null,null,1,null);
INSERT INTO `country` VALUES (null, 'BA', 'Bosnia and Herzegovina',null,null,1,null);
INSERT INTO `country` VALUES (null, 'BW', 'Botswana',null,null,1,null);
INSERT INTO `country` VALUES (null, 'BV', 'Bouvet Island',null,null,1,null);
INSERT INTO `country` VALUES (null, 'BR', 'Brazil',null,null,1,null);
INSERT INTO `country` VALUES (null, 'IO', 'British Indian Ocean Territory',null,null,1,null);
INSERT INTO `country` VALUES (null, 'BN', 'Brunei Darussalam',null,null,1,null);
INSERT INTO `country` VALUES (null, 'BG', 'Bulgaria',null,null,1,null);
INSERT INTO `country` VALUES (null, 'BF', 'Burkina Faso',null,null,1,null);
INSERT INTO `country` VALUES (null, 'BI', 'Burundi',null,null,1,null);
INSERT INTO `country` VALUES (null, 'KH', 'Cambodia',null,null,1,null);
INSERT INTO `country` VALUES (null, 'CM', 'Cameroon',null,null,1,null);
INSERT INTO `country` VALUES (null, 'CA', 'Canada',null,null,1,null);
INSERT INTO `country` VALUES (null, 'CV', 'Cape Verde',null,null,1,null);
INSERT INTO `country` VALUES (null, 'KY', 'Cayman Islands',null,null,1,null);
INSERT INTO `country` VALUES (null, 'CF', 'Central African Republic',null,null,1,null);
INSERT INTO `country` VALUES (null, 'TD', 'Chad',null,null,1,null);
INSERT INTO `country` VALUES (null, 'CL', 'Chile',null,null,1,null);
INSERT INTO `country` VALUES (null, 'CN', 'China',null,null,1,null);
INSERT INTO `country` VALUES (null, 'CX', 'Christmas Island',null,null,1,null);
INSERT INTO `country` VALUES (null, 'CC', 'Cocos (Keeling) Islands',null,null,1,null);
INSERT INTO `country` VALUES (null, 'CO', 'Colombia',null,null,1,null);
INSERT INTO `country` VALUES (null, 'KM', 'Comoros',null,null,1,null);
INSERT INTO `country` VALUES (null, 'CG', 'Congo',null,null,1,null);
INSERT INTO `country` VALUES (null, 'CK', 'Cook Islands',null,null,1,null);
INSERT INTO `country` VALUES (null, 'CR', 'Costa Rica',null,null,1,null);
INSERT INTO `country` VALUES (null, 'HR', 'Croatia (Hrvatska)',null,null,1,null);
INSERT INTO `country` VALUES (null, 'CU', 'Cuba',null,null,1,null);
INSERT INTO `country` VALUES (null, 'CY', 'Cyprus',null,null,1,null);
INSERT INTO `country` VALUES (null, 'CZ', 'Czech Republic',null,null,1,null);
INSERT INTO `country` VALUES (null, 'DK', 'Denmark',null,null,1,null);
INSERT INTO `country` VALUES (null, 'DJ', 'Djibouti',null,null,1,null);
INSERT INTO `country` VALUES (null, 'DM', 'Dominica',null,null,1,null);
INSERT INTO `country` VALUES (null, 'DO', 'Dominican Republic',null,null,1,null);
INSERT INTO `country` VALUES (null, 'TP', 'East Timor',null,null,1,null);
INSERT INTO `country` VALUES (null, 'EC', 'Ecuador',null,null,1,null);
INSERT INTO `country` VALUES (null, 'EG', 'Egypt',null,null,1,null);
INSERT INTO `country` VALUES (null, 'SV', 'El Salvador',null,null,1,null);
INSERT INTO `country` VALUES (null, 'GQ', 'Equatorial Guinea',null,null,1,null);
INSERT INTO `country` VALUES (null, 'ER', 'Eritrea',null,null,1,null);
INSERT INTO `country` VALUES (null, 'EE', 'Estonia',null,null,1,null);
INSERT INTO `country` VALUES (null, 'ET', 'Ethiopia',null,null,1,null);
INSERT INTO `country` VALUES (null, 'FK', 'Falkland Islands (Malvinas)',null,null,1,null);
INSERT INTO `country` VALUES (null, 'FO', 'Faroe Islands',null,null,1,null);
INSERT INTO `country` VALUES (null, 'FJ', 'Fiji',null,null,1,null);
INSERT INTO `country` VALUES (null, 'FI', 'Finland',null,null,1,null);
INSERT INTO `country` VALUES (null, 'FR', 'France',null,null,1,null);
INSERT INTO `country` VALUES (null, 'FX', 'France, Metropolitan',null,null,1,null);
INSERT INTO `country` VALUES (null, 'GF', 'French Guiana',null,null,1,null);
INSERT INTO `country` VALUES (null, 'PF', 'French Polynesia',null,null,1,null);
INSERT INTO `country` VALUES (null, 'TF', 'French Southern Territories',null,null,1,null);
INSERT INTO `country` VALUES (null, 'GA', 'Gabon',null,null,1,null);
INSERT INTO `country` VALUES (null, 'GM', 'Gambia',null,null,1,null);
INSERT INTO `country` VALUES (null, 'GE', 'Georgia',null,null,1,null);
INSERT INTO `country` VALUES (null, 'DE', 'Germany',null,null,1,null);
INSERT INTO `country` VALUES (null, 'GH', 'Ghana',null,null,1,null);
INSERT INTO `country` VALUES (null, 'GI', 'Gibraltar',null,null,1,null);
INSERT INTO `country` VALUES (null, 'GK', 'Guernsey',null,null,1,null);
INSERT INTO `country` VALUES (null, 'GR', 'Greece',null,null,1,null);
INSERT INTO `country` VALUES (null, 'GL', 'Greenland',null,null,1,null);
INSERT INTO `country` VALUES (null, 'GD', 'Grenada',null,null,1,null);
INSERT INTO `country` VALUES (null, 'GP', 'Guadeloupe',null,null,1,null);
INSERT INTO `country` VALUES (null, 'GU', 'Guam',null,null,1,null);
INSERT INTO `country` VALUES (null, 'GT', 'Guatemala',null,null,1,null);
INSERT INTO `country` VALUES (null, 'GN', 'Guinea',null,null,1,null);
INSERT INTO `country` VALUES (null, 'GW', 'Guinea-Bissau',null,null,1,null);
INSERT INTO `country` VALUES (null, 'GY', 'Guyana',null,null,1,null);
INSERT INTO `country` VALUES (null, 'HT', 'Haiti',null,null,1,null);
INSERT INTO `country` VALUES (null, 'HM', 'Heard and Mc Donald Islands',null,null,1,null);
INSERT INTO `country` VALUES (null, 'HN', 'Honduras',null,null,1,null);
INSERT INTO `country` VALUES (null, 'HK', 'Hong Kong',null,null,1,null);
INSERT INTO `country` VALUES (null, 'HU', 'Hungary',null,null,1,null);
INSERT INTO `country` VALUES (null, 'IS', 'Iceland',null,null,1,null);
INSERT INTO `country` VALUES (null, 'IN', 'India',null,null,1,null);
INSERT INTO `country` VALUES (null, 'IM', 'Isle of Man',null,null,1,null);
INSERT INTO `country` VALUES (null, 'ID', 'Indonesia',null,null,1,null);
INSERT INTO `country` VALUES (null, 'IR', 'Iran (Islamic Republic of)',null,null,1,null);
INSERT INTO `country` VALUES (null, 'IQ', 'Iraq',null,null,1,null);
INSERT INTO `country` VALUES (null, 'IE', 'Ireland',null,null,1,null);
INSERT INTO `country` VALUES (null, 'IL', 'Israel',null,null,1,null);
INSERT INTO `country` VALUES (null, 'IT', 'Italy',null,null,1,null);
INSERT INTO `country` VALUES (null, 'CI', 'Ivory Coast',null,null,1,null);
INSERT INTO `country` VALUES (null, 'JE', 'Jersey',null,null,1,null);
INSERT INTO `country` VALUES (null, 'JM', 'Jamaica',null,null,1,null);
INSERT INTO `country` VALUES (null, 'JP', 'Japan',null,null,1,null);
INSERT INTO `country` VALUES (null, 'JO', 'Jordan',null,null,1,null);
INSERT INTO `country` VALUES (null, 'KZ', 'Kazakhstan',null,null,1,null);
INSERT INTO `country` VALUES (null, 'KE', 'Kenya',null,null,1,null);
INSERT INTO `country` VALUES (null, 'KI', 'Kiribati',null,null,1,null);
INSERT INTO `country` VALUES (null, 'KP', 'Korea, Democratic People''s Republic of',null,null,1,null);
INSERT INTO `country` VALUES (null, 'KR', 'Korea, Republic of',null,null,1,null);
INSERT INTO `country` VALUES (null, 'XK', 'Kosovo',null,null,1,null);
INSERT INTO `country` VALUES (null, 'KW', 'Kuwait',null,null,1,null);
INSERT INTO `country` VALUES (null, 'KG', 'Kyrgyzstan',null,null,1,null);
INSERT INTO `country` VALUES (null, 'LA', 'Lao People''s Democratic Republic',null,null,1,null);
INSERT INTO `country` VALUES (null, 'LV', 'Latvia',null,null,1,null);
INSERT INTO `country` VALUES (null, 'LB', 'Lebanon',null,null,1,null);
INSERT INTO `country` VALUES (null, 'LS', 'Lesotho',null,null,1,null);
INSERT INTO `country` VALUES (null, 'LR', 'Liberia',null,null,1,null);
INSERT INTO `country` VALUES (null, 'LY', 'Libyan Arab Jamahiriya',null,null,1,null);
INSERT INTO `country` VALUES (null, 'LI', 'Liechtenstein',null,null,1,null);
INSERT INTO `country` VALUES (null, 'LT', 'Lithuania',null,null,1,null);
INSERT INTO `country` VALUES (null, 'LU', 'Luxembourg',null,null,1,null);
INSERT INTO `country` VALUES (null, 'MO', 'Macau',null,null,1,null);
INSERT INTO `country` VALUES (null, 'MK', 'Macedonia',null,null,1,null);
INSERT INTO `country` VALUES (null, 'MG', 'Madagascar',null,null,1,null);
INSERT INTO `country` VALUES (null, 'MW', 'Malawi',null,null,1,null);
INSERT INTO `country` VALUES (null, 'MY', 'Malaysia',null,null,1,null);
INSERT INTO `country` VALUES (null, 'MV', 'Maldives',null,null,1,null);
INSERT INTO `country` VALUES (null, 'ML', 'Mali',null,null,1,null);
INSERT INTO `country` VALUES (null, 'MT', 'Malta',null,null,1,null);
INSERT INTO `country` VALUES (null, 'MH', 'Marshall Islands',null,null,1,null);
INSERT INTO `country` VALUES (null, 'MQ', 'Martinique',null,null,1,null);
INSERT INTO `country` VALUES (null, 'MR', 'Mauritania',null,null,1,null);
INSERT INTO `country` VALUES (null, 'MU', 'Mauritius',null,null,1,null);
INSERT INTO `country` VALUES (null, 'TY', 'Mayotte',null,null,1,null);
INSERT INTO `country` VALUES (null, 'MX', 'Mexico',null,null,1,null);
INSERT INTO `country` VALUES (null, 'FM', 'Micronesia, Federated States of',null,null,1,null);
INSERT INTO `country` VALUES (null, 'MD', 'Moldova, Republic of',null,null,1,null);
INSERT INTO `country` VALUES (null, 'MC', 'Monaco',null,null,1,null);
INSERT INTO `country` VALUES (null, 'MN', 'Mongolia',null,null,1,null);
INSERT INTO `country` VALUES (null, 'ME', 'Montenegro',null,null,1,null);
INSERT INTO `country` VALUES (null, 'MS', 'Montserrat',null,null,1,null);
INSERT INTO `country` VALUES (null, 'MA', 'Morocco',null,null,1,null);
INSERT INTO `country` VALUES (null, 'MZ', 'Mozambique',null,null,1,null);
INSERT INTO `country` VALUES (null, 'MM', 'Myanmar',null,null,1,null);
INSERT INTO `country` VALUES (null, 'NA', 'Namibia',null,null,1,null);
INSERT INTO `country` VALUES (null, 'NR', 'Nauru',null,null,1,null);
INSERT INTO `country` VALUES (null, 'NP', 'Nepal',null,null,1,null);
INSERT INTO `country` VALUES (null, 'NL', 'Netherlands',null,null,1,null);
INSERT INTO `country` VALUES (null, 'AN', 'Netherlands Antilles',null,null,1,null);
INSERT INTO `country` VALUES (null, 'NC', 'New Caledonia',null,null,1,null);
INSERT INTO `country` VALUES (null, 'NZ', 'New Zealand',null,null,1,null);
INSERT INTO `country` VALUES (null, 'NI', 'Nicaragua',null,null,1,null);
INSERT INTO `country` VALUES (null, 'NE', 'Niger',null,null,1,null);
INSERT INTO `country` VALUES (null, 'NG', 'Nigeria',null,null,1,null);
INSERT INTO `country` VALUES (null, 'NU', 'Niue',null,null,1,null);
INSERT INTO `country` VALUES (null, 'NF', 'Norfolk Island',null,null,1,null);
INSERT INTO `country` VALUES (null, 'MP', 'Northern Mariana Islands',null,null,1,null);
INSERT INTO `country` VALUES (null, 'NO', 'Norway',null,null,1,null);
INSERT INTO `country` VALUES (null, 'OM', 'Oman',null,null,1,null);
INSERT INTO `country` VALUES (null, 'PK', 'Pakistan',null,null,1,null);
INSERT INTO `country` VALUES (null, 'PW', 'Palau',null,null,1,null);
INSERT INTO `country` VALUES (null, 'PS', 'Palestine',null,null,1,null);
INSERT INTO `country` VALUES (null, 'PA', 'Panama',null,null,1,null);
INSERT INTO `country` VALUES (null, 'PG', 'Papua New Guinea',null,null,1,null);
INSERT INTO `country` VALUES (null, 'PY', 'Paraguay',null,null,1,null);
INSERT INTO `country` VALUES (null, 'PE', 'Peru',null,null,1,null);
INSERT INTO `country` VALUES (null, 'PH', 'Philippines',null,null,1,null);
INSERT INTO `country` VALUES (null, 'PN', 'Pitcairn',null,null,1,null);
INSERT INTO `country` VALUES (null, 'PL', 'Poland',null,null,1,null);
INSERT INTO `country` VALUES (null, 'PT', 'Portugal',null,null,1,null);
INSERT INTO `country` VALUES (null, 'PR', 'Puerto Rico',null,null,1,null);
INSERT INTO `country` VALUES (null, 'QA', 'Qatar',null,null,1,null);
INSERT INTO `country` VALUES (null, 'RE', 'Reunion',null,null,1,null);
INSERT INTO `country` VALUES (null, 'RO', 'Romania',null,null,1,null);
INSERT INTO `country` VALUES (null, 'RU', 'Russian Federation',null,null,1,null);
INSERT INTO `country` VALUES (null, 'RW', 'Rwanda',null,null,1,null);
INSERT INTO `country` VALUES (null, 'KN', 'Saint Kitts and Nevis',null,null,1,null);
INSERT INTO `country` VALUES (null, 'LC', 'Saint Lucia',null,null,1,null);
INSERT INTO `country` VALUES (null, 'VC', 'Saint Vincent and the Grenadines',null,null,1,null);
INSERT INTO `country` VALUES (null, 'WS', 'Samoa',null,null,1,null);
INSERT INTO `country` VALUES (null, 'SM', 'San Marino',null,null,1,null);
INSERT INTO `country` VALUES (null, 'ST', 'Sao Tome and Principe',null,null,1,null);
INSERT INTO `country` VALUES (null, 'SA', 'Saudi Arabia',null,null,1,null);
INSERT INTO `country` VALUES (null, 'SN', 'Senegal',null,null,1,null);
INSERT INTO `country` VALUES (null, 'RS', 'Serbia',null,null,1,null);
INSERT INTO `country` VALUES (null, 'SC', 'Seychelles',null,null,1,null);
INSERT INTO `country` VALUES (null, 'SL', 'Sierra Leone',null,null,1,null);
INSERT INTO `country` VALUES (null, 'SG', 'Singapore',null,null,1,null);
INSERT INTO `country` VALUES (null, 'SK', 'Slovakia',null,null,1,null);
INSERT INTO `country` VALUES (null, 'SI', 'Slovenia',null,null,1,null);
INSERT INTO `country` VALUES (null, 'SB', 'Solomon Islands',null,null,1,null);
INSERT INTO `country` VALUES (null, 'SO', 'Somalia',null,null,1,null);
INSERT INTO `country` VALUES (null, 'ZA', 'South Africa',null,null,1,null);
INSERT INTO `country` VALUES (null, 'GS', 'South Georgia South Sandwich Islands',null,null,1,null);
INSERT INTO `country` VALUES (null, 'ES', 'Spain',null,null,1,null);
INSERT INTO `country` VALUES (null, 'LK', 'Sri Lanka',null,null,1,null);
INSERT INTO `country` VALUES (null, 'SH', 'St. Helena',null,null,1,null);
INSERT INTO `country` VALUES (null, 'PM', 'St. Pierre and Miquelon',null,null,1,null);
INSERT INTO `country` VALUES (null, 'SD', 'Sudan',null,null,1,null);
INSERT INTO `country` VALUES (null, 'SR', 'Suriname',null,null,1,null);
INSERT INTO `country` VALUES (null, 'SJ', 'Svalbard and Jan Mayen Islands',null,null,1,null);
INSERT INTO `country` VALUES (null, 'SZ', 'Swaziland',null,null,1,null);
INSERT INTO `country` VALUES (null, 'SE', 'Sweden',null,null,1,null);
INSERT INTO `country` VALUES (null, 'CH', 'Switzerland',null,null,1,null);
INSERT INTO `country` VALUES (null, 'SY', 'Syrian Arab Republic',null,null,1,null);
INSERT INTO `country` VALUES (null, 'TW', 'Taiwan',null,null,1,null);
INSERT INTO `country` VALUES (null, 'TJ', 'Tajikistan',null,null,1,null);
INSERT INTO `country` VALUES (null, 'TZ', 'Tanzania, United Republic of',null,null,1,null);
INSERT INTO `country` VALUES (null, 'TH', 'Thailand',null,null,1,null);
INSERT INTO `country` VALUES (null, 'TG', 'Togo',null,null,1,null);
INSERT INTO `country` VALUES (null, 'TK', 'Tokelau',null,null,1,null);
INSERT INTO `country` VALUES (null, 'TO', 'Tonga',null,null,1,null);
INSERT INTO `country` VALUES (null, 'TT', 'Trinidad and Tobago',null,null,1,null);
INSERT INTO `country` VALUES (null, 'TN', 'Tunisia',null,null,1,null);
INSERT INTO `country` VALUES (null, 'TR', 'Turkey',null,null,1,null);
INSERT INTO `country` VALUES (null, 'TM', 'Turkmenistan',null,null,1,null);
INSERT INTO `country` VALUES (null, 'TC', 'Turks and Caicos Islands',null,null,1,null);
INSERT INTO `country` VALUES (null, 'TV', 'Tuvalu',null,null,1,null);
INSERT INTO `country` VALUES (null, 'UG', 'Uganda',null,null,1,null);
INSERT INTO `country` VALUES (null, 'UA', 'Ukraine',null,null,1,null);
INSERT INTO `country` VALUES (null, 'AE', 'United Arab Emirates',null,null,1,null);
INSERT INTO `country` VALUES (null, 'GB', 'United Kingdom',null,null,1,null);
INSERT INTO `country` VALUES (null, 'US', 'United States',null,null,1,null);
INSERT INTO `country` VALUES (null, 'UM', 'United States minor outlying islands',null,null,1,null);
INSERT INTO `country` VALUES (null, 'UY', 'Uruguay',null,null,1,null);
INSERT INTO `country` VALUES (null, 'UZ', 'Uzbekistan',null,null,1,null);
INSERT INTO `country` VALUES (null, 'VU', 'Vanuatu',null,null,1,null);
INSERT INTO `country` VALUES (null, 'VA', 'Vatican City State',null,null,1,null);
INSERT INTO `country` VALUES (null, 'VE', 'Venezuela',null,null,1,null);
INSERT INTO `country` VALUES (null, 'VN', 'Vietnam',null,null,1,null);
INSERT INTO `country` VALUES (null, 'VG', 'Virgin Islands (British)',null,null,1,null);
INSERT INTO `country` VALUES (null, 'VI', 'Virgin Islands (U.S.)',null,null,1,null);
INSERT INTO `country` VALUES (null, 'WF', 'Wallis and Futuna Islands',null,null,1,null);
INSERT INTO `country` VALUES (null, 'EH', 'Western Sahara',null,null,1,null);
INSERT INTO `country` VALUES (null, 'YE', 'Yemen',null,null,1,null);
INSERT INTO `country` VALUES (null, 'ZR', 'Zaire',null,null,1,null);
INSERT INTO `country` VALUES (null, 'ZM', 'Zambia',null,null,1,null);
INSERT INTO `country` VALUES (null, 'ZW', 'Zimbabwe',null,null,1,null);";

        DB::unprepared($sql);
    }
}
