<?php

use Illuminate\Database\Seeder;

class PermissionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //add default permissions
        $permissions = [
            [
                'id'=>1,
                'name'=>'home_page',
                'display_name'=>'Home Page',
                'description'=>'HomePageController@index',
                'resource'=>'App\Http\Controllers\HomePageController@index',
                'is_common'=>1,
            ],
            [
                'id'=>2,
                'name'=>'contact_form',
                'display_name'=>'Contact Form',
                'description'=>'HomePageController@postContact',
                'resource'=>'App\Http\Controllers\HomePageController@postContact',
                'is_common'=>1,
            ],
            [
                'id'=>3,
                'name'=>'get_login',
                'display_name'=>'Get Login',
                'description'=>'UserController@getLogin',
                'resource'=>'App\Http\Controllers\UserController@getLogin',
                'is_common'=>1,
            ],
            [
                'id'=>4,
                'name'=>'post_login',
                'display_name'=>'Post Login',
                'description'=>'UserController@postLogin',
                'resource'=>'App\Http\Controllers\UserController@postLogin',
                'is_common'=>1,
            ],
            [
                'id'=>5,
                'name'=>'user_register',
                'display_name'=>'User Register',
                'description'=>'UserController@postRegister',
                'resource'=>'App\Http\Controllers\UserController@postRegister',
                'is_common'=>1,
            ],
            [
                'id'=>6,
                'name'=>'view_dashboard',
                'display_name'=>'View Dashboard',
                'description'=>'UserController@getDashboard',
                'resource'=>'App\Http\Controllers\UserController@getDashboard',
                'is_common'=>0,
            ],
            [
                'id'=>7,
                'name'=>'view_profile',
                'display_name'=>'View Profile',
                'description'=>'UserController@getProfile',
                'resource'=>'App\Http\Controllers\UserController@getProfile',
                'is_common'=>0,
            ],
            [
                'id'=>8,
                'name'=>'view_profile_settings',
                'display_name'=>'View Profile Settings',
                'description'=>'UserController@getSettings',
                'resource'=>'App\Http\Controllers\UserController@getSettings',
                'is_common'=>0,
            ],
            [
                'id'=>9,
                'name'=>'save_profile_settings',
                'display_name'=>'Save Profile Settings',
                'description'=>'UserController@saveSettings',
                'resource'=>'App\Http\Controllers\UserController@saveSettings',
                'is_common'=>0,
            ],
            [
                'id'=>10,
                'name'=>'create_new_page',
                'display_name'=>'Create New Page',
                'description'=>'CMSController@createNewPage',
                'resource'=>'App\Http\Controllers\CMSController@createNewPage',
                'is_common'=>0,
            ],
            [
                'id'=>11,
                'name'=>'view_all_pages',
                'display_name'=>'View All Pages',
                'description'=>'CMSController@getPages',
                'resource'=>'App\Http\Controllers\CMSController@getPages',
                'is_common'=>0,
            ],
            [
                'id'=>12,
                'name'=>'view_page',
                'display_name'=>'View Page',
                'description'=>'CMSController@viewPage',
                'resource'=>'App\Http\Controllers\CMSController@viewPage',
                'is_common'=>0,
            ],
            [
                'id'=>13,
                'name'=>'remove_page',
                'display_name'=>'Remove Page',
                'description'=>'CMSController@removePage',
                'resource'=>'App\Http\Controllers\CMSController@removePage',
                'is_common'=>0,
            ],
            [
                'id'=>14,
                'name'=>'save_page',
                'display_name'=>'Save Page',
                'description'=>'CMSController@savePage',
                'resource'=>'App\Http\Controllers\CMSController@savePage',
                'is_common'=>0,
            ],
            [
                'id'=>15,
                'name'=>'create_new_user',
                'display_name'=>'Create New User',
                'description'=>'UserController@createNewUser',
                'resource'=>'App\Http\Controllers\UserController@createNewUser',
                'is_common'=>0,
            ],
            [
                'id'=>16,
                'name'=>'view_staff_list',
                'display_name'=>'View Staff List',
                'description'=>'UserController@getUsers',
                'resource'=>'App\Http\Controllers\UserController@getUsers',
                'is_common'=>0,
            ],
            [
                'id'=>17,
                'name'=>'remove_user',
                'display_name'=>'Remove User',
                'description'=>'UserController@removeUser',
                'resource'=>'App\Http\Controllers\UserController@removeUser',
                'is_common'=>0,
            ],
            [
                'id'=>18,
                'name'=>'view_user',
                'display_name'=>'View User',
                'description'=>'UserController@viewUser',
                'resource'=>'App\Http\Controllers\UserController@viewUser',
                'is_common'=>0,
            ],
            [
                'id'=>19,
                'name'=>'save_user',
                'display_name'=>'Save User',
                'description'=>'UserController@saveUser',
                'resource'=>'App\Http\Controllers\UserController@saveUser',
                'is_common'=>0,
            ],
            [
                'id'=>20,
                'name'=>'create_new_role',
                'display_name'=>'Create New Role',
                'description'=>'RoleController@createNewRole',
                'resource'=>'App\Http\Controllers\RoleController@createNewRole',
                'is_common'=>0,
            ],
            [
                'id'=>21,
                'name'=>'view_roles_list',
                'display_name'=>'View Roles List',
                'description'=>'RoleController@getRoles',
                'resource'=>'App\Http\Controllers\RoleController@getRoles',
                'is_common'=>0,
            ],
            [
                'id'=>22,
                'name'=>'remove_role',
                'display_name'=>'Remove Role',
                'description'=>'RoleController@removeRole',
                'resource'=>'App\Http\Controllers\RoleController@removeRole',
                'is_common'=>0,
            ],
            [
                'id'=>23,
                'name'=>'view_role',
                'display_name'=>'View Role',
                'description'=>'RoleController@viewRole',
                'resource'=>'App\Http\Controllers\RoleController@viewRole',
                'is_common'=>0,
            ],
            [
                'id'=>24,
                'name'=>'save_role',
                'display_name'=>'Save Role',
                'description'=>'RoleController@saveRole',
                'resource'=>'App\Http\Controllers\RoleController@saveRole',
                'is_common'=>0,
            ],
            [
                'id'=>25,
                'name'=>'view_clients_list',
                'display_name'=>'View Clients List',
                'description'=>'UserController@getClients',
                'resource'=>'App\Http\Controllers\UserController@getClients',
                'is_common'=>0,
            ],
            [
                'id'=>26,
                'name'=>'view_user_activity_list',
                'display_name'=>'View User Activity List',
                'description'=>'ActivityController@getActivities',
                'resource'=>'App\Http\Controllers\ActivityController@getActivities',
                'is_common'=>0,
            ],
            [
                'id'=>27,
                'name'=>'view_users_countonline',
                'display_name'=>'View Users Count Online',
                'description'=>'UserController@getActiveUserCount',
                'resource'=>'App\Http\Controllers\UserController@getActiveUserCount',
                'is_common'=>0,
            ],
            [
                'id'=>28,
                'name'=>'view_ajax_notifications_listitems',
                'display_name'=>'View Ajax Notifications Listitems',
                'description'=>'ActivityController@getNotifyActivities',
                'resource'=>'App\Http\Controllers\ActivityController@getNotifyActivities',
                'is_common'=>0,
            ],
            [
                'id'=>29,
                'name'=>'view_all_notification_activites',
                'display_name'=>'View All Notifications Activities',
                'description'=>'ActivityController@viewAllNotifyActivities',
                'resource'=>'App\Http\Controllers\ActivityController@viewAllNotifyActivities',
                'is_common'=>0,
            ],
            [
                'id'=>30,
                'name'=>'save_system_configurations',
                'display_name'=>'Save System Configurations',
                'description'=>'SettingsController@saveConfigurations',
                'resource'=>'App\Http\Controllers\SettingsController@saveConfigurations',
                'is_common'=>0,
            ],
            [
                'id'=>31,
                'name'=>'view_system_configurations',
                'display_name'=>'View System Configurations',
                'description'=>'SettingsController@getConfigurations',
                'resource'=>'App\Http\Controllers\SettingsController@getConfigurations',
                'is_common'=>0,
            ],
            [
                'id'=>32,
                'name'=>'create_new_email_template',
                'display_name'=>'Create New Email Template',
                'description'=>'EmailTemplatesController@createNewEmailTemplate',
                'resource'=>'App\Http\Controllers\EmailTemplatesController@createNewEmailTemplate',
                'is_common'=>0,
            ],
            [
                'id'=>33,
                'name'=>'view_email_templates',
                'display_name'=>'View Email Templates',
                'description'=>'EmailTemplatesController@getEmailTemplates',
                'resource'=>'App\Http\Controllers\EmailTemplatesController@getEmailTemplates',
                'is_common'=>0,
            ],
            [
                'id'=>34,
                'name'=>'view_email_template',
                'display_name'=>'View Email Template',
                'description'=>'EmailTemplatesController@viewEmailTemplate',
                'resource'=>'App\Http\Controllers\EmailTemplatesController@viewEmailTemplate',
                'is_common'=>0,
            ],
            [
                'id'=>35,
                'name'=>'remove_email_template',
                'display_name'=>'Remove Email Template',
                'description'=>'EmailTemplatesController@removeEmailTemplate',
                'resource'=>'App\Http\Controllers\EmailTemplatesController@removeEmailTemplate',
                'is_common'=>0,
            ],
            [
                'id'=>36,
                'name'=>'save_email_template',
                'display_name'=>'Save Email Template',
                'description'=>'EmailTemplatesController@saveEmailTemplate',
                'resource'=>'App\Http\Controllers\EmailTemplatesController@saveEmailTemplate',
                'is_common'=>0,
            ],
            [
                'id'=>37,
                'name'=>'is_valid_current_password',
                'display_name'=>'Is Valid Current Password',
                'description'=>'UserController@isValidCurrentPassword',
                'resource'=>'App\Http\Controllers\UserController@isValidCurrentPassword',
                'is_common'=>0,
            ],
            [
                'id'=>38,
                'name'=>'view_email_configurations',
                'display_name'=>'View Email Configurations',
                'description'=>'SettingsController@getEmailConfigurations',
                'resource'=>'App\Http\Controllers\SettingsController@getEmailConfigurations',
                'is_common'=>0,
            ]
        ];

        DB::table('permissions')->delete();

        foreach($permissions as $permission){
            DB::table('permissions')->insert($permission);
        }
    }
}
